apiVersion: v1
kind: Service
metadata:
  name: acc-sample-webapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: acc-sample-webapp
---
apiVersion: v1
kind: Pod
metadata:
  name: acc-sample-webapp
  labels:
    app: acc-sample-webapp
spec:
  restartPolicy: Never
  initContainers:
  - image: <ATTESTATION_IMAGE_NAME>
    name: acc-attestation-reporter
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /sys/kernel/security
        name: tcg
      - mountPath: /dev/tpmrm0
        name: tpmrm0
      - name: logs
        mountPath: /logs
  containers:
  - image: <APP_IMAGE_NAME>
    name: <APP_NAME>
    imagePullPolicy: Always
    volumeMounts:
      - name: logs
        mountPath: /logs
  nodeSelector:
    agentpool: confidential
    kubernetes.azure.com/security-type: ConfidentialVM
  volumes:
    - name: logs
      emptyDir: {}
    - name: tcg
      hostPath:
        path: /sys/kernel/security
    - name: tpmrm0
      hostPath:
        path: /dev/tpmrm0
