apiVersion: v1
kind: Service
metadata:
  name: acc-sample-webapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: acc-sample-webapp
---
apiVersion: v1
kind: Pod
metadata:
  name: acc-sample-webapp
  labels:
    app: acc-sample-webapp
spec:
  containers:
  - image: <APP_IMAGE_NAME>
    imagePullPolicy: Always
    name: acc-sample-webapp
  nodeSelector:
    agentpool: confidential
